stages:
  - setup
  - build
  - deploy

variables:
  # DOCKER_IMAGE_NAME: $CI_PROJECT_TITLE:$CI_COMMIT_REF_SLUG
  DOCKER_IMAGE_NAME: devops/$CI_PROJECT_TITLE:v1.0.$CI_PIPELINE_IID
  REMOTE_USER: root
  REMOTE_HOST: "192.168.23.31"
  REMOTE_DIR: "/opt/monitor/webhook"

### RULES REUSED VIA YAML ANCHORS:
.if-release-branch: &if-release-branch
  if: '($CI_COMMIT_REF_NAME =~ /release/) && $CI_PIPELINE_SOURCE != "merge_request_event"'

.if-release-branch-merge: &if-release-branch-merge
  if: '($CI_COMMIT_REF_NAME =~ /release/) && $CI_PIPELINE_SOURCE == "merge_request_event"'

.if-dev-int-branch: &if-dev-int-branch
  if: '($CI_COMMIT_REF_NAME =~ /develop/) && $CI_PIPELINE_SOURCE != "merge_request_event" && $DEPLOYER != "test"'

.if-test-int-branch: &if-test-int-branch
  if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_PIPELINE_SOURCE == "web" && $DEPLOYER == "test"'

.if-other-branch: &if-other-branch
  if: '($CI_COMMIT_REF_NAME =~ /feature/ || $CI_COMMIT_REF_NAME =~ /hotfix/) && $CI_PIPELINE_SOURCE == "merge_request_event"'

.if-master-branch: &if-master-branch
  if: '($CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH) && $CI_PIPELINE_SOURCE != "merge_request_event"'

.if-merge-request: &if-merge-request
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.if-match-trigger-branch: &if-match-trigger-branch
  if: '($CI_COMMIT_REF_NAME == $TRIGGER_BRANCH) && $CI_PIPELINE_SOURCE != "merge_request_event"'


workflow:
  rules:
    # Trigger conditions inherited from base-devsecops
    - <<: *if-other-branch
      when: never
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - <<: *if-dev-int-branch # dev-*
    - <<: *if-test-int-branch # test
    - <<: *if-release-branch # release-*
    - <<: *if-release-branch-merge
    - <<: *if-master-branch # master
    - <<: *if-merge-request

# setup Stage
setup-env:
  stage: setup
  rules:
    # dynamic generates the image tag based on the branch or event triggers the pipeline
    - <<: *if-dev-int-branch # develop-*
      # Trigger condition for DEV deployment, if committing some code to the branch which prefix is "develop", then trigger current pipeline
      variables:
        IMAGE_TAG: "${CI_COMMIT_REF_NAME}-${VERSION}"
    - <<: *if-test-int-branch # test-*
      variables:
        IMAGE_TAG: "${CI_COMMIT_REF_NAME}"
    - <<: *if-release-branch # release-*
      variables:
        IMAGE_TAG: "${CI_COMMIT_REF_NAME}"
    - <<: *if-release-branch-merge # release-*
      variables:
        IMAGE_TAG: "${CI_COMMIT_REF_NAME}"
    - <<: *if-other-branch # feature-* || hotfix-*
      variables:
        IMAGE_TAG: "${CI_COMMIT_REF_NAME}-${VERSION}"
    - <<: *if-master-branch # master
      variables:
        IMAGE_TAG: "${VERSION}"
    - <<: *if-merge-request # feature-* || hotfix-*
      variables:
        IMAGE_TAG: "${CI_COMMIT_REF_NAME}-${VERSION}"
  script:
    - echo "VERSION=${VERSION}"
    - echo "IMAGE_TAG=${IMAGE_TAG}"


docker-build:
  # Use the official docker image.
  image: docker:cli
  stage: build
  services:
    - docker:dind
  tags:
      - shared-PD4-runner-46
  script:
    #- export
    - echo "docker build --pull -t $REGISTRY_URL/$DOCKER_IMAGE_NAME . "
    - docker build --pull -t $REGISTRY_URL/$DOCKER_IMAGE_NAME . 
    - echo "docker push $REGISTRY_URL/$DOCKER_IMAGE_NAME"
    - docker push $REGISTRY_URL/$DOCKER_IMAGE_NAME
  # Run this job in a branch where a Dockerfile exists
  rules:
    - <<: *if-master-branch # master
      exists:
        - Dockerfile

deploy-docker:
  stage: deploy
  tags:
      - shared-PD4-runner-46
  script:
    #- export
    - |
      ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << EOF
      #!/bin/bash
      sed -n "s|    image: .*|    image: ${REGISTRY_URL}/${DOCKER_IMAGE_NAME}|p" $REMOTE_DIR/docker-compose.yml
      sed -i "s|    image: .*|    image: ${REGISTRY_URL}/${DOCKER_IMAGE_NAME}|g" $REMOTE_DIR/docker-compose.yml
      docker-compose -f $REMOTE_DIR/docker-compose.yml down
      docker-compose -f $REMOTE_DIR/docker-compose.yml up -d
      EOF
  # Run this job in a branch where a Dockerfile exists
  after_script:
    # - docker rmi dangling
    - |
      IMAGE_IDS=$(docker images --format "{{.ID}} {{.Repository}}" | grep "${REGISTRY_URL}/${DOCKER_IMAGE}" | awk '{print $1}')
      if [ -z "$IMAGE_IDS" ]; then
        echo "No images found for ${IMAGE_NAME}";
      else
        echo "Removing images:";
        for IMAGE_ID in $IMAGE_IDS; do
          # 检查镜像是否被任何容器使用
          CONTAINER_IDS=$(docker ps -a --filter "ancestor=$IMAGE_ID" --format "{{.ID}}")
          if [ -z "$CONTAINER_IDS" ]; then
            echo "Removing image $IMAGE_ID"
            docker rmi -f $IMAGE_ID
          else
            echo "Image $IMAGE_ID is in use by containers: $CONTAINER_IDS. Skipping."
          fi
        done;
      fi
  rules:
    - <<: *if-master-branch # master