stages:
  - build
  - deploy

variables:
  # DOCKER_IMAGE_NAME: $CI_PROJECT_TITLE:$CI_COMMIT_REF_SLUG
  DOCKER_IMAGE_NAME: devops/$CI_PROJECT_TITLE:v1.0.$CI_PIPELINE_IID
  REMOTE_HOST: 192.168.23.31
  REMOTE_DIR: /opt/monitor/webhook/


docker-build:
  # Use the official docker image.
  image: docker:cli
  stage: build
  services:
    - docker:dind
  tags:
      - shared-PD4-runner-46
  script:
    #- export
    - echo "docker build --pull -t $REGISTRY_URL/$DOCKER_IMAGE_NAME . "
    - docker build --pull -t $REGISTRY_URL/$DOCKER_IMAGE_NAME . 
    - echo "docker push $REGISTRY_URL/$DOCKER_IMAGE_NAME"
    - docker push $REGISTRY_URL/$DOCKER_IMAGE_NAME
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy-docker:
  stage: deploy
  tags:
      - shared-PD4-runner-46
  script:
    #- export
    - docker-compose -f $REMOTE_DIR/docker-compose.yml down
    - sed -i "s|{{DOCKER_IMAGE_NAME}}|$DOCKER_IMAGE_NAME|g" $REMOTE_DIR/docker-compose.yml
    - docker-compose -f $REMOTE_DIR/docker-compose.yml up -d
  # Run this job in a branch where a Dockerfile exists